### PR TITLE
Fix [Yanagishima] bytes is negative

### LINKED ISSUE #367: [Yanagishima] bytes is negative
**Yanagishima version**: 23.0

**Presto version**:trino-361

**conf/application.yml**:default

**JVM version** (`java -version`):openjdk 11

**Server OS version** (`uname -a` if on a Unix-like system):
```shell
Linux ****** 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Client OS version**:windows 10

**Browser**:Edge

**Description of the problem including expected versus actual behavior**:
> expected return query result ，but error message “ bytes is negative”

**Steps to reproduce**:

 1. Run a query
 2. And result file size over 2G
 

**Provide logs (if relevant)**:
```java
2021/09/15 12:32:36.202 +0800 ERROR [QueryHistoryUserController] [Yanagishima] bytes is negative
java.lang.IllegalArgumentException: bytes is negative
        at io.airlift.units.Preconditions.checkArgument(Preconditions.java:26)
        at io.airlift.units.DataSize.<init>(DataSize.java:102)
        at io.airlift.units.DataSize.ofBytes(DataSize.java:68)
        at yanagishima.util.FormatUtil.toSuccinctDataSize(FormatUtil.java:15)
        at yanagishima.controller.QueryHistoryUserController.get(QueryHistoryUserController.java:57)
        at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)

```
	
**Provide screenshots (if relevant)**:
image

### PR DESCRIPTION
**Pull request by siu91**
Closed #367

Signed-off-by: siu91 <gongshiwen@gmail.com>

### CODE REVIEW

**Comment by siu91** [comment]
@wyukawa @ebyhr

**Comment by wyukawa** [comment]
Please fix CI error and add test in `FormatUtilTest` like `assertEquals("2GB", ...`

**Comment by siu91** [comment]
> Please fix CI error and add test in `FormatUtilTest` like `assertEquals("2GB", ...`

add test in `FormatUtilTest`

**Review by wyukawa — APPROVED** [review]
LGTM

**Pull request merged**
