### PR TITLE
Add GitHub Page using mkdocs

### PR DESCRIPTION
**Pull request by ebyhr**
Install mkdocs to the local environment
```
pip install mkdocs
```

Way to run mkdocs in local environment (http://127.0.0.1:8000)
```
mkdocs serve
```

Push generated pages to `gh-pages` branch
```
mkdocs gh-deploy
```

Generated page: https://ebyhr.github.io/yanagishima

### CODE REVIEW

**Comment by wyukawa** [comment]
Thanks!

**Comment by ebyhr** [comment]
@wyukawa We need to run `mkdocs gh-deploy` to publish a site and set `gh-pages` as GitHub pages' source in Settings as below. 
Screen Shot 2019-12-02 at 18 04 22

**Comment by wyukawa** [comment]
done!
https://yanagishima.github.io/yanagishima/

**Comment by ebyhr** [comment]
Thanks!

**Pull request merged**
