### PR TITLE
Upgrade to Presto 0.214

### PR DESCRIPTION
**Pull request by Bcpoole**
Updated PrestoServiceImpl to handle changes to Presto's StatementClient.
Updated project Version to 17.0.

### CODE REVIEW

**Comment by mcsrainbow** [comment]
Nice fix!

**Comment by wyukawa** [comment]
Thank you for contribution.
But I'm afraid I can't merge due to the following reasons
- ```com.sun.org.apache.xpath.internal.operations.Bool``` is not necessary
- This pull request contains multiple feature changes(version up, upgrade presto-client, upgrade presto-parser)
- presto 0.214 is not lastet

I maintain SPA and API codes separately in yanagishima.
When I bump up, I push SPA codes.
It's not easy to bump up.

Anyway, I fixed in d4ee755 and closed this pull request.

**Comment by mcsrainbow** [comment]
@wyukawa may I ask that how could I git clone the version with this fix?
The latest tag is still "28 days ago", thank you very much.

**Comment by wyukawa** [comment]
I have just released 17.0.
Please try this version.

**Pull request closed without merging**
