### PR TITLE
Fix MySQL long living connection issue

### LINKED ISSUE #63: Mysql jdbc errors after no connecting to mysql for one day
Bug report

**yanagishima version**: 21.0

**presto version**: 318

**conf/yanagishima.properties**:
```
# yanagishima web port
jetty.port=8080

# backend RDMS
database.type=mysql
mysql.host=yanagishima-mysql
mysql.port=3306
mysql.database=yanagishima
mysql.user=yanagishima
mysql.password=xxxxxxxxxxxxxxxxxxx

# 30 minutes. If presto query exceeds this time, yanagishima cancel the query.
presto.query.max-run-time-seconds=1800

# 1GB. If presto query result file size exceeds this value, yanagishima cancel the query.
presto.max-result-file-byte-size=1073741824

# you can specify freely. But you need to specify same name to presto.coordinator.server.[...] and presto.redirect.server.[...] and catalog.[...] and schema.[...]
presto.datasources=your-presto
auth.your-presto=false

# presto coordinator url
presto.coordinator.server.your-presto=http://presto-coordinator:8080

# almost same as presto coordinator url. If you use reverse proxy, specify it
presto.redirect.server.your-presto=http://presto.xxxxxxxx.test:30080/ui

# presto catalog name
catalog.your-presto=hive

# presto schema name
schema.your-presto=default

# if query result exceeds this limit, to show rest of result is skipped
select.limit=500

# http header name for audit log
audit.http.header.name=some.auth.header
use.audit.http.header.name=false

# limit to convert from tsv to values query
to.values.query.limit=500

# authorization feature
check.datasource=false
hive.jdbc.url.your-hive=jdbc:hive2://hiveserver2:10000/default
hive.jdbc.user.your-hive=yanagishima
hive.jdbc.password.your-hive=yanagishima
hive.query.max-run-time-seconds=3600
hive.query.max-run-time-seconds.your-hive=3600
resource.manager.url.your-hive=http://resourcemanager:8088
sql.query.engines=presto,hive
hive.datasources=your-hive
hive.disallowed.keywords.your-hive=insert,drop

# 1GB. If hive query result file size exceeds this value, yanagishima cancel the query.
hive.max-result-file-byte-size=1073741824
hive.setup.query.path.your-hive=/usr/local/yanagishima/conf/hive_setup_query_your-hive
```

**JVM version** (`java -version`): openjdk version "11.0.3" 2019-04-16 LTS

**Server OS version** (`uname -a` if on a Unix-like system): Linux yanagishima-6d84dd6667-sl6q9 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Client OS version**: Darwin w022581712182m.local 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin

**Browser**: Chrome

**Description of the problem including expected versus actual behavior**:

When accessing yanagishima UI after haven't accessing the UI for one day,

Expected: Display UI without error popup.
Actual: Error popup "Please contact admin"  displays

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Deploy yanagishima server with mysql backend, and access the ui.
 2. Don't access the yanagishima ui for 1 day.
 3. Access the yanagishima ui

**Provide logs (if relevant)**:
Server log

```
2019/08/27 03:05:27.805 +0000 ERROR [RichSQLException] [Yanagishima] SQLException: No operations allowed after connection closed. SELECT engine, query_id, fetch_result_time_string, query_string FROM query WHERE engine='presto' and datasource='your-presto' and query_id IN () []                                                   [1/36290]
2019/08/27 03:05:27.806 +0000 WARN [ServletHandler] [Yanagishima] /query
me.geso.jdbcutils.UncheckedRichSQLException: SQL Exception: No operations allowed after connection closed.:SELECT engine, query_id, fetch_result_time_string, query_string FROM query WHERE engine='presto' and datasource='your-presto' and query_id IN ()([])
        at me.geso.tinyorm.TinyORM.prepareStatement(TinyORM.java:146)
        at me.geso.tinyorm.TinyORM.searchBySQL(TinyORM.java:294)
        at me.geso.tinyorm.TinyORM.searchBySQL(TinyORM.java:281)
        at yanagishima.servlet.QueryServlet.doPost(QueryServlet.java:142)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
        at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
        at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at yanagishima.filter.YanagishimaFilter.doFilter(YanagishimaFilter.java:38)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: me.geso.jdbcutils.RichSQLException: SQL Exception: No operations allowed after connection closed.:SELECT engine, query_id, fetch_result_time_string, query_string FROM query WHERE engine='presto' and datasource='your-presto' and query_id IN ()([])
        at me.geso.jdbcutils.UncheckedRichSQLException.<init>(UncheckedRichSQLException.java:13)
        ... 37 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
        at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1192)
        at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1187)
        at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4067)
        at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4036)
        at me.geso.tinyorm.TinyORM.prepareStatement(TinyORM.java:140)
        ... 36 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 62,523,444 milliseconds ago.  The last packet sent successfully to the server was 62,523,444 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring an
d/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3751)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2512)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
        at me.geso.tinyorm.TinyORM.searchBySQL(TinyORM.java:296)
        ... 35 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
        at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
        at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3733)
        ... 41 more
```

**Provide screenshots (if relevant)**:
No screen shot. Sorry.

I think it will be resolved by adding "autoReconnect=true" to mysql url.
https://github.com/yanagishima/yanagishima/blob/487e70a3b5ac75a29b44d24647e41c96dbb0062f/src/main/java/yanagishima/provider/ConnectionProvider.java#L29

Thanks in advance.

### PR DESCRIPTION
**Pull request by ebyhr**
Fixes #63

### CODE REVIEW

**Comment by wyukawa** [comment]
Thanks!

But I checkouted this pull request in local, executed with IntelliJ, accessed by SPA but the following error occurred.

Could you please check?

```
2020/12/09 16:37:26.150 +0900 INFO [HikariDataSource] [Yanagishima] HikariPool-1 - Starting...
2020/12/09 16:37:27.482 +0900 INFO [HikariDataSource] [Yanagishima] HikariPool-1 - Start completed.
2020/12/09 16:37:28.132 +0900 INFO [log] [Yanagishima] Logging initialized @3048ms to org.eclipse.jetty.util.log.Slf4jLog
2020/12/09 16:37:28.217 +0900 INFO [YanagishimaServer] [Yanagishima] Yanagishima Server started...
2020/12/09 16:37:28.220 +0900 INFO [Server] [Yanagishima] jetty-9.4.25.v20191220; built: 2019-12-20T17:00:00.294Z; git: a9729c7e7f33a459d2616a8f9e9ba8a90f432e95; jvm 11.0.6+10
2020/12/09 16:37:28.264 +0900 INFO [session] [Yanagishima] DefaultSessionIdManager workerName=node0
2020/12/09 16:37:28.264 +0900 INFO [session] [Yanagishima] No SessionScavenger set, using defaults
2020/12/09 16:37:28.266 +0900 INFO [session] [Yanagishima] node0 Scavenging every 600000ms
2020/12/09 16:37:28.595 +0900 INFO [ContextHandler] [Yanagishima] Started o.e.j.s.ServletContextHandler@1f38957{/,file:///Users/.../yanagishima/web/,AVAILABLE}
2020/12/09 16:37:28.617 +0900 INFO [AbstractConnector] [Yanagishima] Started ServerConnector@352c308{HTTP/1.1,[http/1.1]}{0.0.0.0:10080}
2020/12/09 16:37:28.617 +0900 INFO [Server] [Yanagishima] Started @3535ms
2020/12/09 16:37:28.620 +0900 INFO [YanagishimaServer] [Yanagishima] Yanagishima Server running port 10080
2020/12/09 16:37:44.231 +0900 INFO [TinyORM] [Yanagishima] Loading class yanagishima.row.Bookmark
2020/12/09 16:37:44.234 +0900 INFO [TinyORM] [Yanagishima] Loading class yanagishima.row.StarredSchema
2020/12/09 16:37:44.255 +0900 ERROR [RichSQLException] [Yanagishima] SQLException: Connection is closed SELECT * FROM `starred_schema` WHERE (datasource = ? AND engine = ? AND catalog = ? AND user = ?) []
2020/12/09 16:37:44.255 +0900 ERROR [RichSQLException] [Yanagishima] SQLException: Connection is closed SELECT * FROM `bookmark` WHERE (datasource = ? AND engine = ? AND user = ?) []
2020/12/09 16:37:44.257 +0900 ERROR [BookmarkUserServlet] [Yanagishima] SQL Exception: Connection is closed:SELECT * FROM `bookmark` WHERE (datasource = ? AND engine = ? AND user = ?)([])
me.geso.jdbcutils.UncheckedRichSQLException: SQL Exception: Connection is closed:SELECT * FROM `bookmark` WHERE (datasource = ? AND engine = ? AND user = ?)([])
	at me.geso.tinyorm.TinyORM.prepareStatement(TinyORM.java:146)
	at me.geso.tinyorm.TinyORM.prepareStatementForRead(TinyORM.java:135)
	at me.geso.tinyorm.ListSelectStatement.execute(ListSelectStatement.java:35)
	at yanagishima.servlet.BookmarkUserServlet.doGet(BookmarkUserServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at yanagishima.filter.YanagishimaFilter.doFilter(YanagishimaFilter.java:35)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: me.geso.jdbcutils.RichSQLException: SQL Exception: Connection is closed:SELECT * FROM `bookmark` WHERE (datasource = ? AND engine = ? AND user = ?)([])
	at me.geso.jdbcutils.UncheckedRichSQLException.<init>(UncheckedRichSQLException.java:13)
	... 47 more
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:515)
	at com.sun.proxy.$Proxy19.prepareStatement(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at me.geso.tinyorm.TinyORM.prepareStatement(TinyORM.java:140)
	... 46 more
```

**Comment by ebyhr** [comment]
Sorry, tested only few cases. Let me fix it.

**Comment by ebyhr** [comment]
@wyukawa Fixed and added some tests.

**Comment by wyukawa** [comment]
Unfortunately, the following error occurred when I deleted star after I added star in schema in treeview 😢 
I guess you need to take care of `delete` pattern.
```
2020/12/10 11:57:22.615 +0900 INFO [YanagishimaServer] [Yanagishima] Yanagishima Server running port 10080
2020/12/10 11:58:11.948 +0900 INFO [TinyORM] [Yanagishima] Loading class yanagishima.row.StarredSchema
2020/12/10 11:58:11.967 +0900 INFO [TinyORM] [Yanagishima] Loading class yanagishima.row.Bookmark
2020/12/10 11:58:12.314 +0900 INFO [TinyORM] [Yanagishima] Loading class yanagishima.row.Query
2020/12/10 11:59:58.068 +0900 ERROR [StarredSchemaServlet] [Yanagishima] java.sql.SQLException: Connection is closed
java.lang.RuntimeException: java.sql.SQLException: Connection is closed
	at me.geso.tinyorm.TinyORM.getIdentifierQuoteString(TinyORM.java:634)
	at me.geso.tinyorm.TinyORM.delete(TinyORM.java:544)
	at me.geso.tinyorm.Row.delete(Row.java:67)
	at yanagishima.servlet.StarredSchemaServlet.doDelete(StarredSchemaServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at yanagishima.filter.YanagishimaFilter.doFilter(YanagishimaFilter.java:35)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:515)
	at com.sun.proxy.$Proxy19.getMetaData(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.getMetaData(ProxyConnection.java:380)
	at com.zaxxer.hikari.pool.HikariProxyConnection.getMetaData(HikariProxyConnection.java)
	at me.geso.tinyorm.TinyORM.getIdentifierQuoteString(TinyORM.java:631)
	... 46 more
2020/12/10 12:00:00.400 +0900 ERROR [StarredSchemaServlet] [Yanagishima] java.sql.SQLException: Connection is closed
java.lang.RuntimeException: java.sql.SQLException: Connection is closed
	at me.geso.tinyorm.TinyORM.getIdentifierQuoteString(TinyORM.java:634)
	at me.geso.tinyorm.TinyORM.delete(TinyORM.java:544)
	at me.geso.tinyorm.Row.delete(Row.java:67)
	at yanagishima.servlet.StarredSchemaServlet.doDelete(StarredSchemaServlet.java:84)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at yanagishima.filter.YanagishimaFilter.doFilter(YanagishimaFilter.java:35)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.SQLException: Connection is closed
	at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:515)
	at com.sun.proxy.$Proxy19.getMetaData(Unknown Source)
	at com.zaxxer.hikari.pool.ProxyConnection.getMetaData(ProxyConnection.java:380)
	at com.zaxxer.hikari.pool.HikariProxyConnection.getMetaData(HikariProxyConnection.java)
	at me.geso.tinyorm.TinyORM.getIdentifierQuoteString(TinyORM.java:631)
	... 46 more
```

By the way, I can check the following diff in force-pushed link from https://github.com/yanagishima/yanagishima/pull/186
https://github.com/yanagishima/yanagishima/compare/1e154a3f2ef83a2e591d2de085342eaeea52ff3f..701ea06b2abf0d70daaf0ecae4f8390c0136c4b2
https://github.com/yanagishima/yanagishima/compare/701ea06b2abf0d70daaf0ecae4f8390c0136c4b2..dca4683ce821aa07a58359ecabd0ad4dd5d5cedb

I think the most important difference is  https://github.com/yanagishima/yanagishima/compare/453a67b396682e20e7abaf1123000d9ae21a3575..dca4683ce821aa07a58359ecabd0ad4dd5d5cedb in terms of `Connection is closed` but I can't find the link in https://github.com/yanagishima/yanagishima/pull/186

I guess I can't find 453a67b396682e20e7abaf1123000d9ae21a3575 without checking out locally before you do force push.

Do you know how to check such kind of diff easily with browser?

If there is no good way, please don't squash because I can't check diff easily.

**Comment by ebyhr** [comment]
Ugh, I was doing grep only `TinyORM` since I supposed this library is similar to JdbcTemplate. But understood it is designed likes ActiveRecord now. 

The cause of no clean force pushed diff is I accidentally pushed twice. I will care of that from next time.

**Comment by ebyhr** [comment]
Updated. Though existing Comment delete logic doesn't check optional, changed to the use `ifPresent`.

**Review by wyukawa — APPROVED** [review]
👍 
It seems to work well in my local and beta environment.
Let's merge, deploy, check in our environment without daily restart.

**Comment by ebyhr** [comment]
Thanks for your detailed review. I was little optimistic for this issue.

**Pull request merged**
